# Generated by Django 2.0.3 on 2018-03-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0002_basicsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicSetting',
            new_name='Market',
        ),
    ]
