# Generated by Django 2.0.3 on 2018-03-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0003_auto_20180313_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='desc_market',
            field=models.TextField(blank=True, default='Welcome to my Market! Here you finded a lot of product special for us.', null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name_market',
            field=models.CharField(blank=True, default='Django Market', max_length=64, null=True),
        ),
    ]
