# Generated by Django 2.0.3 on 2018-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value_attribute',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
