# Generated by Django 2.0.3 on 2018-03-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_attribute_value_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='name_attribute',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='value_attribute',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_product',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_manager.GroupAttribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_manager.GroupCategory'),
            preserve_default=False,
        ),
    ]
