# Generated by Django 2.0.3 on 2018-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_auto_20180313_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupattribute',
            name='value',
        ),
    ]
