# Generated by Django 2.0.3 on 2018-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0008_auto_20180313_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='/media/default.png', null=True, upload_to=''),
        ),
    ]
