# Generated by Django 2.0.3 on 2018-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0009_auto_20180313_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to=''),
        ),
    ]
