# Generated by Django 2.0.3 on 2018-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0010_auto_20180313_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('usd', '$'), ('eur', '€'), ('rub', '₽')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
