# Generated by Django 2.0.3 on 2018-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0012_auto_20180313_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('₽', 'RUB')], default='$', max_length=3, verbose_name=''),
        ),
    ]
